// src/app/admin/orders/[id]/packing-slip/page.tsx
import { notFound } from "next/navigation";
import { getOrder } from "@/lib/orderStore";

export const runtime = "nodejs";

function money(n: number) {
  return `£${n.toFixed(2)}`;
}

export default async function PackingSlipPage({
  params,
}: {
  params: { id: string };
}) {
  const order = await getOrder(params.id);
  if (!order) return notFound();

  const a = order.shippingAddress || null;

  const addrLines = [
    order.shippingName || null,
    a?.line1 || null,
    a?.line2 || null,
    a?.city || null,
    a?.state || null,
    a?.postalCode || null,
    a?.country || null,
  ].filter(Boolean) as string[];

  return (
    <div
      style={{
        padding: 24,
        maxWidth: 900,
        margin: "0 auto",
        fontFamily: "Arial, sans-serif",
        color: "#111",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", gap: 24 }}>
        <div>
          <h1 style={{ margin: 0 }}>Packing Slip</h1>
          <div style={{ marginTop: 8 }}>
            <div>
              <strong>Order:</strong> {order.id}
            </div>
            <div>
              <strong>Date:</strong>{" "}
              {new Date(order.createdAt).toLocaleString("en-GB")}
            </div>
            <div>
              <strong>Status:</strong> {order.status}
            </div>
            {order.customerEmail ? (
              <div>
                <strong>Customer:</strong> {order.customerEmail}
              </div>
            ) : null}
            {order.trackingNumber ? (
              <div>
                <strong>Tracking:</strong> {order.trackingNumber}
              </div>
            ) : null}
          </div>
        </div>

        <div
          style={{
            minWidth: 320,
            border: "1px solid #ddd",
            borderRadius: 10,
            padding: 16,
          }}
        >
          <div style={{ fontWeight: 800, marginBottom: 8 }}>Ship to</div>

          {addrLines.length ? (
            <div style={{ lineHeight: 1.5 }}>
              {addrLines.map((line, i) => (
                <div key={i}>{line}</div>
              ))}
              {a?.phone ? <div style={{ marginTop: 6 }}>Phone: {a.phone}</div> : null}
            </div>
          ) : (
            <div>Shipping address not available.</div>
          )}
        </div>
      </div>

      <hr style={{ margin: "20px 0" }} />

      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr style={{ textAlign: "left" }}>
            <th style={{ padding: "10px 0", borderBottom: "2px solid #eee" }}>
              Item
            </th>
            <th style={{ padding: "10px 0", borderBottom: "2px solid #eee" }}>
              Qty
            </th>
            <th style={{ padding: "10px 0", borderBottom: "2px solid #eee" }}>
              Unit
            </th>
            <th style={{ padding: "10px 0", borderBottom: "2px solid #eee" }}>
              Line
            </th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((it, idx) => (
            <tr key={idx}>
              <td style={{ padding: "10px 0", borderBottom: "1px solid #eee" }}>
                <div style={{ fontWeight: 700 }}>{it.name}</div>

                {it.customText ? (
                  <div style={{ marginTop: 4, color: "#444" }}>
                    Text: “{it.customText}” • Font: {it.font || "Default"}
                  </div>
                ) : null}

                {it.uploadUrl ? (
                  <div style={{ marginTop: 6 }}>
                    Upload: <span style={{ color: "#555" }}>{it.uploadUrl}</span>
                  </div>
                ) : null}
              </td>

              <td style={{ padding: "10px 0", borderBottom: "1px solid #eee" }}>
                {it.quantity}
              </td>
              <td style={{ padding: "10px 0", borderBottom: "1px solid #eee" }}>
                {money(it.unitPrice)}
              </td>
              <td style={{ padding: "10px 0", borderBottom: "1px solid #eee" }}>
                {money(it.lineTotal)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop: 16, textAlign: "right" }}>
        <div>Subtotal: {money(order.subtotal)}</div>
        <div>Shipping: {money(order.shipping)}</div>
        <div style={{ fontSize: 18, fontWeight: 900, marginTop: 6 }}>
          Total: {money(order.total)}
        </div>
      </div>

      <hr style={{ margin: "20px 0" }} />

      <div style={{ fontSize: 12, color: "#555" }}>
        <div>Generated by Generations in Making admin.</div>
      </div>
    </div>
  );
}
